server:
  port: 8081
logging:
  level:
    root: debug
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          #???????
          jwk-set-uri: http://auth-server:8080/oauth2/jwks
