server:
  port: 80
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    # password: 123456
    #设置默认访问的数据库
    database: 1
    #设置超时时间
    timeout: 2000
    lettuce:
      pool:
        #最大允许连接数
        max-active: 100
        #最小空闲连接数,最少准备5个可用连接在连接池候着
        min-idle: 5
        #最大空闲连接数,空闲连接超过10个后自动释放
        max-idle: 10
        #当连接池到达上限后,最多等待30秒尝试获取连接,超时报错
        max-wait: 30000
    # 哨兵使用的配置
#    sentinel:
#      nodes: 192.168.31.110:26379, 192.168.31.111:26379, 192.168.31.112:26379
#      master: mymaster

    # 集群使用的配置
    cluster:
      nodes: 192.168.31.110:6379, 192.168.31.111:6379, 192.168.31.112:6379
      max-redirects: 3
  cache:
    redis:
      cache-null-values: true